version: "3"
networks:
  whylogs:
    driver: bridge
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
        - whylogs
    ports:
      - $ZOOKEEPER_PORT:$ZOOKEEPER_PORT
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
        - whylogs
    ports:
      - $EXTERNAL_KAFKA_PORT:$EXTERNAL_KAFKA_PORT
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:$ZOOKEEPER_PORT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:$INTERNAL_KAFKA_PORT,EXTERNAL://:$EXTERNAL_KAFKA_PORT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:$INTERNAL_KAFKA_PORT,EXTERNAL://localhost:$EXTERNAL_KAFKA_PORT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_NUM_PARTITIONS=10
    depends_on:
      - zookeeper

  whylogs:
    image: 'whylabs/whylogs:latest'
    networks:
        - whylogs
    ports:
      -  $WHYLOGS_CONTAINER_PORT:$WHYLOGS_CONTAINER_PORT
    environment:
      - KAFKA_ENABLED=true
      - 'KAFKA_TOPIC_DATASET_IDS={"wow-ah": "$MODEL_ID"}'
      - KAFKA_BOOTSTRAP_SERVERS=["http://kafka:$INTERNAL_KAFKA_PORT"]
      - KAFKA_GROUP_ID=whylogs
      - KAFKA_TOPICS=["wow-ah"]
      - KAFKA_CONSUMER_THREADS=10
      - PROFILE_STORAGE_MODE=IN_MEMORY
      - REQUEST_QUEUEING_ENABLED=false
      - PORT=$WHYLOGS_CONTAINER_PORT
      - WHYLOGS_PERIOD=HOURS
      - UPLOAD_DESTINATION=WHYLABS
      - WHYLABS_API_KEY=$WHYLABS_API_KEY
      - CONTAINER_API_KEY=$CONTAINER_KEY
      - ORG_ID=$ORG_ID
    depends_on:
      - kafka

  data-poller:
    image: 'naddeoa/wow-ah-data-poller'
    networks:
        - whylogs
    environment:
      - API_CLIENT_ID=$API_CLIENT_ID
      - API_CLIENT_SECRET=$API_CLIENT_SECRET
      - KAFKA_BOOTSTRAP_SERVER=kafka:$INTERNAL_KAFKA_PORT
    depends_on:
      - kafka


