/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package WowAHKafkaBlog

import org.junit.jupiter.api.Test


//import kotlin.test.Test

class AppTest {
//    @Test
    fun test() {

        val auctions = data.get("auctions")
        forPath(auctions) { id, key, value ->
            println("$key -> $value")
        }
    }

//    @Test
    fun testMap() {
        val auctions = data.get("auctions")
        val items = toFlatDict(auctions)
        items.forEach{
            println(it)
        }
    }
}
